# Generated by Django 2.1 on 2019-05-25 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0004_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ocena', models.IntegerField(choices=[(1, ' * '), (2, ' ** '), (3, ' *** '), (4, ' **** '), (5, ' ***** ')])),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('author', models.CharField(max_length=64, null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('status', models.IntegerField(choices=[(1, 'w trakcie pisania'), (2, 'czeka na akceptację redaktora'), (3, 'opublikowany')])),
                ('poczatek_emisji', models.DateTimeField(null=True)),
                ('koniec_emisji', models.DateTimeField(null=True)),
            ],
        ),
    ]
