# Generated by Django 2.1 on 2019-05-29 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0002_movie_director'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='director',
        ),
        migrations.AddField(
            model_name='person',
            name='position',
            field=models.IntegerField(choices=[(-1, 'not defined'), (0, 'actor'), (1, 'director'), (2, 'screenplay')], default=-1),
        ),
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.IntegerField(choices=[(-1, 'non defined'), (0, 'horror'), (1, 'sci-fi'), (2, 'romans')], default=-1),
        ),
        migrations.AlterField(
            model_name='person',
            name='first_name',
            field=models.CharField(default='No', max_length=32),
        ),
        migrations.AlterField(
            model_name='person',
            name='last_name',
            field=models.CharField(default='Name', max_length=32),
        ),
    ]
