# Generated by Django 2.1 on 2019-05-29 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0003_auto_20190529_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='genre',
            field=models.ManyToManyField(to='homework.Genre'),
        ),
        migrations.AddField(
            model_name='movie',
            name='starring',
            field=models.ManyToManyField(to='homework.Person'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(default='None', max_length=32),
        ),
    ]
