# Generated by Django 2.1 on 2019-05-29 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0004_auto_20190529_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='rating',
            field=models.IntegerField(choices=[(1, ' * '), (2, ' ** '), (3, ' *** '), (4, ' **** '), (5, ' ***** ')], default=1),
        ),
    ]
